### ISSUE TITLE
お？

### ISSUE THREAD

**Issue by hina-ch** [temochiz-lab/mysandobox#15]
もしかして出来た？

**Comment by temochiz-lab** [comment]
惜しい！
issueがプロジェクトに紐づいていないので、プロジェクト側からこのissueを追加する必要があります。
最初からプロジェクト側でissue作成すれば、この一手間無しです。

**Comment by hina-ch** [comment]
理由が分からないでいました！
またやってみます

**Comment by hina-ch** [comment]
> https://github.com/users/temochiz-lab/projects/4
コピーして貼っちゃだめなのか。

**Comment by hina-ch** [comment]
[https://github.com/users/temochiz-lab/projects/4](url)

**Comment by temochiz-lab** [comment]
https://github.com/users/temochiz-lab/projects/4/views/1
から、
+ Additem → add item from repository → で「お? #15」を登録できませんか？

**Comment by hina-ch** [comment]
additem は見つけました！、、、が、その先のadd item from repository が分からないでいます。

なんかできる？かも？もうすこしやってみます 

望月さん、明日は出張で夜遅くなるじゃないですか！
気になると思うので、私も続きは明日にします。
おやすみなさい。
気をつけて行ってきてください。

**Comment by temochiz-lab** [comment]
スマホからやってみました。
一応できるけど画面が小さすぎて無理ですね。
PCからやった方が良いです💦

**Comment by hina-ch** [comment]
望月さん

今ほど、再度スマホでも探してみましたが、わかりませんでした。

今夜、明日平野さんにお話する前の、私自身の感想を、LINEに書き込みますね！

手持ちのもの、高速充電のものでも皆、低速充電にしかなりません。

明日の１８時過ぎに届くよう手配してるので、日曜日からは安心かと。

よろしくお願い致します。

2023年9月8日(金) 8:03 T.Mochizuki ***@***.***>:

**Comment by temochiz-lab** [comment]
みんながスマホ前提のツールもあるんですが、無料だと最大10人の縛りとかあって、こっちとどっちが良いのか、、

**Comment by hina-ch** [comment]
「どうやらスマホ自体が壊れてる？」と、今、私のスマホは旦那が確認していて、
私の手元に戻ってきません。
その直前に、音声ファイルを共有してみましたが、どうでしょう？

それとスマホ前提のツールもあるとのことですが、私、github以外のアプリ選択はしなくてもよいのでは？と、
思っています。
ここのコメント欄は、とても扱いやすいと思うので。皆さん楽しめるのでは？と思っています。

2023年9月8日(金) 9:56 T.Mochizuki ***@***.***>:

**Comment by temochiz-lab** [comment]
音声ファイル、共有大丈夫です！
平野さんもPC使える様子だし、いけるかなー

**Comment by hina-ch** [comment]
よかったです！

情報過多によりオツムパンク寸前。
後程LINEからスタートしますー

2023年9月9日(土) 9:55 T.Mochizuki ***@***.***>:

**Comment by hina-ch** [comment]
いろいろ観ていて、気になることをメモっておきます。
なんでここ？というのは、望月さんの邪魔にならないところで、でも共有する時にはお手軽ってところで😁

◎研修委員が団体旅行の手配で四苦八苦しています。蒔田先生と平野さん達研修委員の言葉が通じてなかった(旅程の意味の取り違え。)
◎他の高校の研修委員がどう対応しているのか知りたがってる
◎フォームで、近隣の高校の研修委員会にアンケート取るのは？面白そう。←思い付いたばかり

◎アンケート、まだ回答期限前ですが。来年春の理事募集前に、学校説明会でのPTAご案内で内容の一部を使いたい。折しも３月、望月さんはお仕事に余裕あり。プロジェクター、プリント校内印刷機(入学式用と300×２回５００枚入り1.５冊分)

◎そういえば、「チラシ」という表現は、先生や本部は「外注印刷物」と捉えるから避ける

**Comment by hina-ch** [comment]
> もしかして出来た？
